"use client";
import Image from "next/image";
import { useEffect, useState } from "react";
import type { CSSProperties } from "react";
import type { StaticImageData } from "next/image";
import { ArrowUpRight, ChevronLeft, ChevronRight, Menu, Send, Star, X } from "lucide-react";
import { salonData as d } from "@/lib/salonData";

const nav = ["HOME","ABOUT","SERVICES","MAKEOVER","GALLERY","REVIEWS","CONTACT"];
const homeImages = { salon: d.services[2].image, makeover: d.services[1].image, styling: d.services[0].image };
const heroSlides = [
 {src:homeImages.salon,alt:"Luxury salon interior with styling stations"},
 {src:homeImages.makeover,alt:"Long-haired client during a premium makeover"},
 {src:homeImages.styling,alt:"Stylist creating a polished salon look"},
];
export default function Home(){
 const [menu,setMenu]=useState(false),[filter,setFilter]=useState("ALL"),[lightbox,setLightbox]=useState<string|StaticImageData|null>(null),[pos,setPos]=useState(51),[sent,setSent]=useState(false),[heroSlide,setHeroSlide]=useState(0);
 const [scrolled,setScrolled]=useState(false); useEffect(()=>{const f=()=>setScrolled(scrollY>40);addEventListener("scroll",f);return()=>removeEventListener("scroll",f)},[]);
 useEffect(()=>{const timer=window.setInterval(()=>setHeroSlide(current=>(current+1)%heroSlides.length),5200);return()=>window.clearInterval(timer)},[]);
 useEffect(()=>{const items=document.querySelectorAll<HTMLElement>(".image-reveal");const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("is-visible");observer.unobserve(entry.target)}})},{threshold:.16,rootMargin:"0px 0px -8%"});items.forEach(item=>observer.observe(item));return()=>observer.disconnect()},[]);
 const gallery=d.gallery.filter(x=>filter==="ALL"||x[0]===filter);
 const jump=(id:string)=>{setMenu(false);document.getElementById(id.toLowerCase())?.scrollIntoView({behavior:"smooth"})}
 return <main>
 <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"BeautySalon",name:d.name,url:"https://www.stylonmakeover.com/",image:d.logo})}} />
 <nav className={`nav ${scrolled?"nav-solid":""}`}><button className="brand" onClick={()=>jump("home")} aria-label="Stylon Makeover home"><Image src={d.logo} alt="Stylon Makeover official logo" width={116} height={116}/></button><div className="navlinks">{nav.map(n=><button key={n} onClick={()=>jump(n)}>{n}</button>)}</div><button className="book-mini" onClick={()=>jump("contact")}>Book appointment <ArrowUpRight size={15}/></button><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Toggle menu">{menu?<X/>:<Menu/>}</button></nav>
 {menu&&<div className="mobile-nav">{nav.map(n=><button key={n} onClick={()=>jump(n)}>{n}</button>)}</div>}
 <section className="hero" id="home"><div className="hero-slides" aria-hidden="true">{heroSlides.map((slide,i)=><Image key={i} src={slide.src} alt="" fill priority={i===0} sizes="100vw" className={`hero-img ${heroSlide===i?"active":""}`}/>)}</div><div className="hero-shade"/><div className="hero-content"><p className="eyebrow"><span/> STYLON MAKEOVER <i>PREMIUM BEAUTY & MAKEOVER STUDIO</i></p><h1>Beauty,<br/><em>redefined.</em></h1><p className="intro">Where style, beauty and confidence come together.</p><div className="hero-actions"><button className="btn light" onClick={()=>jump("contact")}>Book an appointment <ArrowUpRight/></button><button className="text-btn" onClick={()=>jump("services")}>Explore services <span>→</span></button></div></div><p className="side-label">SCROLL TO DISCOVER <span/></p></section>
 <section className="about section" id="about"><div className="section-number">01</div><div className="about-img image-wrap image-reveal" style={{"--reveal-delay":"80ms"} as CSSProperties}><Image src={homeImages.styling} fill sizes="(max-width:700px) 100vw, 45vw" alt="Professional beauty styling"/></div><div className="about-copy"><p className="eyebrow dark"><span/> OUR PHILOSOPHY</p><h2>Your style.<br/><em>Your signature.</em></h2><p>At Stylon Makeover, every look begins with listening. We pair an individual point of view with meticulous technique to create beauty that feels unmistakably yours.</p><div className="pillars">{[["Personalized","A look shaped around you."],["Professional","Considered craft, every time."],["Precise","The beauty lives in the details."]].map(([a,b])=><div key={a}><b>{a}</b><small>{b}</small></div>)}</div></div></section>
 <section className="services section" id="services"><p className="eyebrow"><span/> EXPLORE OUR CRAFT</p><h2>The art of<br/><em>transformation.</em></h2><div className="service-grid">{d.services.map((s,i)=><article className="service-card image-reveal" style={{"--reveal-delay":`${i*110}ms`} as CSSProperties} key={s.title}><Image src={s.image} alt={`${s.title} service`} fill sizes="(max-width:700px) 82vw, 25vw"/><div className="card-shade"/><div><small>0{i+1}</small><h3>{s.title}</h3><p>{s.items}</p><ArrowUpRight/></div></article>)}</div></section>
 <section className="campaign image-reveal" id="makeover"><Image src={homeImages.makeover} fill sizes="100vw" alt="Editorial makeover portrait"/><div className="campaign-shade"/><div><p className="eyebrow"><span/> SIGNATURE MAKEOVER</p><h2>Transform<br/>your <em>look.</em></h2><p>From everyday elegance to unforgettable occasions.</p><button className="btn light" onClick={()=>jump("contact")}>Discover makeovers <ArrowUpRight/></button></div></section>
 <section className="transform section"><div><p className="eyebrow dark"><span/> BEFORE & AFTER</p><h2>The<br/><em>transformation.</em></h2><p>Explore the craft behind every Stylon look.</p></div><div className="compare image-reveal" onPointerMove={e=>{if(e.buttons) setPos(Math.max(4,Math.min(96,(e.clientX-e.currentTarget.getBoundingClientRect().left)/e.currentTarget.clientWidth*100)))}}><Image src={homeImages.makeover} fill alt="After makeover" sizes="(max-width:700px) 100vw, 65vw"/><div className="before" style={{width:`${pos}%`}}><Image src={homeImages.styling} fill alt="Before styling" sizes="(max-width:700px) 100vw, 65vw"/></div><div className="slider" style={{left:`${pos}%`}}><span>↔</span></div><b className="before-label">BEFORE</b><b className="after-label">AFTER</b></div></section>
 <section className="gallery section" id="gallery"><div className="gallery-head"><div><p className="eyebrow dark"><span/> THE STYLON JOURNAL</p><h2>Beauty in<br/><em>focus.</em></h2></div><div className="filters">{["ALL","HAIR","MAKEUP","BRIDAL","BEAUTY","SALON"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div><div className="masonry">{gallery.map(([type,url],i)=><button className={`gallery-item g${i%5} image-reveal`} style={{"--reveal-delay":`${i*90}ms`} as CSSProperties} onClick={()=>setLightbox(url)} key={`${type}-${i}`}><Image src={url} alt={`${type} gallery image`} fill sizes="(max-width:700px) 50vw, 33vw"/><span>{type} <ArrowUpRight size={15}/></span></button>)}</div></section>
 <section className="details section"><div className="section-number">02</div><h2>Details make<br/><em>the difference.</em></h2><div className="feature-list">{["Personalized Experience","Professional Styling","Premium Beauty Care","Attention to Detail","Comfortable Environment","Occasion-Ready Looks"].map((x,i)=><div key={x}><small>0{i+1}</small><span>{x}</span><ArrowUpRight size={18}/></div>)}</div></section>
 <section className="reviews section" id="reviews"><p className="eyebrow"><span/> TESTIMONIALS</p><h2>Words from<br/><em>our clients.</em></h2><div className="review-grid">{d.testimonials.map((t,i)=><article key={t}><div className="stars">{Array.from({length:5}).map((_,x)=><Star size={14} fill="currentColor" key={x}/>)}</div><blockquote>“{t}”</blockquote><small>EDITABLE DEMO CONTENT · 0{i+1}</small></article>)}</div></section>
 <section className="cta"><div className="glow pink"/><div className="glow cyan"/><p className="eyebrow"><span/> STYLON MAKEOVER</p><h2>Ready for your<br/><em>next look?</em></h2><p>Your transformation starts here.</p><button className="btn light" onClick={()=>jump("contact")}>Book your appointment <ArrowUpRight/></button></section>
 <section className="contact section" id="contact"><div className="contact-copy"><p className="eyebrow dark"><span/> APPOINTMENTS</p><h2>Let&apos;s create<br/><em>your moment.</em></h2><p>Send a request and the Stylon team will be in touch to confirm availability. Your appointment is not confirmed until then.</p><div className="contact-data"><p>ADDRESS <b>{d.contact.address}</b></p><p>CONTACT <b>{d.contact.phone}<br/>{d.contact.email}</b></p><p>HOURS <b>{d.contact.hours}</b></p></div></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}><div className="form-grid">{[["name","Name","text"],["phone","Phone","tel"],["email","Email","email"],["service","Service","text"],["date","Preferred Date","date"],["time","Preferred Time","time"]].map(([n,l,t])=><label key={n}>{l}<input name={n} type={t} required/></label>)}</div><label>Message<textarea name="message" rows={4}/></label><button className="btn dark" type="submit">Request appointment <Send size={16}/></button>{sent&&<p className="sent">Request captured locally — connect this form to your booking provider to receive submissions.</p>}</form></section>
 <footer><Image src={d.logo} width={165} height={165} alt="Stylon Makeover official logo"/><p>Beauty. Style. Confidence.</p><div>{nav.map(n=><button onClick={()=>jump(n)} key={n}>{n}</button>)}</div><small>© 2026 Stylon Makeover. All Rights Reserved.</small></footer>
 {lightbox&&<div className="lightbox" role="dialog" aria-modal="true"><button onClick={()=>setLightbox(null)} aria-label="Close gallery"><X/></button><Image src={lightbox} alt="Expanded gallery image" fill sizes="100vw"/></div>}
 {d.whatsapp&&<a className="whatsapp" href={`https://wa.me/${d.whatsapp}?text=${encodeURIComponent("Hello Stylon Makeover, I would like to book an appointment.")}`} aria-label="Chat on WhatsApp">◔</a>}
 </main>
}
